// Generated by gencpp from file floribot_engines/encoder_params.msg
// DO NOT EDIT!


#ifndef FLORIBOT_ENGINES_MESSAGE_ENCODER_PARAMS_H
#define FLORIBOT_ENGINES_MESSAGE_ENCODER_PARAMS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace floribot_engines
{
template <class ContainerAllocator>
struct encoder_params_
{
  typedef encoder_params_<ContainerAllocator> Type;

  encoder_params_()
    : header()
    , index(0)
    , count(0)
    , count_change(0)
    , time(0)  {
    }
  encoder_params_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , index(0)
    , count(0)
    , count_change(0)
    , time(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _index_type;
  _index_type index;

   typedef int32_t _count_type;
  _count_type count;

   typedef int32_t _count_change_type;
  _count_change_type count_change;

   typedef int32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::floribot_engines::encoder_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::floribot_engines::encoder_params_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_params_

typedef ::floribot_engines::encoder_params_<std::allocator<void> > encoder_params;

typedef boost::shared_ptr< ::floribot_engines::encoder_params > encoder_paramsPtr;
typedef boost::shared_ptr< ::floribot_engines::encoder_params const> encoder_paramsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::floribot_engines::encoder_params_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::floribot_engines::encoder_params_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::floribot_engines::encoder_params_<ContainerAllocator1> & lhs, const ::floribot_engines::encoder_params_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.index == rhs.index &&
    lhs.count == rhs.count &&
    lhs.count_change == rhs.count_change &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::floribot_engines::encoder_params_<ContainerAllocator1> & lhs, const ::floribot_engines::encoder_params_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace floribot_engines

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::floribot_engines::encoder_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::floribot_engines::encoder_params_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::floribot_engines::encoder_params_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::floribot_engines::encoder_params_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::floribot_engines::encoder_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::floribot_engines::encoder_params_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::floribot_engines::encoder_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cdd1a63f64eb1a145c6b4f3cd6e0681b";
  }

  static const char* value(const ::floribot_engines::encoder_params_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcdd1a63f64eb1a14ULL;
  static const uint64_t static_value2 = 0x5c6b4f3cd6e0681bULL;
};

template<class ContainerAllocator>
struct DataType< ::floribot_engines::encoder_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "floribot_engines/encoder_params";
  }

  static const char* value(const ::floribot_engines::encoder_params_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::floribot_engines::encoder_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 index\n"
"int32 count\n"
"int32 count_change\n"
"int32 time\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::floribot_engines::encoder_params_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::floribot_engines::encoder_params_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.index);
      stream.next(m.count);
      stream.next(m.count_change);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_params_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::floribot_engines::encoder_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::floribot_engines::encoder_params_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "count_change: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count_change);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLORIBOT_ENGINES_MESSAGE_ENCODER_PARAMS_H
