// Generated by gencpp from file floribot_engines/interface_kit.msg
// DO NOT EDIT!


#ifndef FLORIBOT_ENGINES_MESSAGE_INTERFACE_KIT_H
#define FLORIBOT_ENGINES_MESSAGE_INTERFACE_KIT_H

#include <ros/service_traits.h>


#include <floribot_engines/interface_kitRequest.h>
#include <floribot_engines/interface_kitResponse.h>


namespace floribot_engines
{

struct interface_kit
{

typedef interface_kitRequest Request;
typedef interface_kitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct interface_kit
} // namespace floribot_engines


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::floribot_engines::interface_kit > {
  static const char* value()
  {
    return "75cbd2a6abfcf442181c14de3598b662";
  }

  static const char* value(const ::floribot_engines::interface_kit&) { return value(); }
};

template<>
struct DataType< ::floribot_engines::interface_kit > {
  static const char* value()
  {
    return "floribot_engines/interface_kit";
  }

  static const char* value(const ::floribot_engines::interface_kit&) { return value(); }
};


// service_traits::MD5Sum< ::floribot_engines::interface_kitRequest> should match
// service_traits::MD5Sum< ::floribot_engines::interface_kit >
template<>
struct MD5Sum< ::floribot_engines::interface_kitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::floribot_engines::interface_kit >::value();
  }
  static const char* value(const ::floribot_engines::interface_kitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::floribot_engines::interface_kitRequest> should match
// service_traits::DataType< ::floribot_engines::interface_kit >
template<>
struct DataType< ::floribot_engines::interface_kitRequest>
{
  static const char* value()
  {
    return DataType< ::floribot_engines::interface_kit >::value();
  }
  static const char* value(const ::floribot_engines::interface_kitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::floribot_engines::interface_kitResponse> should match
// service_traits::MD5Sum< ::floribot_engines::interface_kit >
template<>
struct MD5Sum< ::floribot_engines::interface_kitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::floribot_engines::interface_kit >::value();
  }
  static const char* value(const ::floribot_engines::interface_kitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::floribot_engines::interface_kitResponse> should match
// service_traits::DataType< ::floribot_engines::interface_kit >
template<>
struct DataType< ::floribot_engines::interface_kitResponse>
{
  static const char* value()
  {
    return DataType< ::floribot_engines::interface_kit >::value();
  }
  static const char* value(const ::floribot_engines::interface_kitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLORIBOT_ENGINES_MESSAGE_INTERFACE_KIT_H
