// Generated by gencpp from file floribot_engines/interface_kitRequest.msg
// DO NOT EDIT!


#ifndef FLORIBOT_ENGINES_MESSAGE_INTERFACE_KITREQUEST_H
#define FLORIBOT_ENGINES_MESSAGE_INTERFACE_KITREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace floribot_engines
{
template <class ContainerAllocator>
struct interface_kitRequest_
{
  typedef interface_kitRequest_<ContainerAllocator> Type;

  interface_kitRequest_()
    : index(0)
    , value_type(0)
    , value(0)  {
    }
  interface_kitRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , value_type(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef int32_t _value_type_type;
  _value_type_type value_type;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::floribot_engines::interface_kitRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::floribot_engines::interface_kitRequest_<ContainerAllocator> const> ConstPtr;

}; // struct interface_kitRequest_

typedef ::floribot_engines::interface_kitRequest_<std::allocator<void> > interface_kitRequest;

typedef boost::shared_ptr< ::floribot_engines::interface_kitRequest > interface_kitRequestPtr;
typedef boost::shared_ptr< ::floribot_engines::interface_kitRequest const> interface_kitRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::floribot_engines::interface_kitRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::floribot_engines::interface_kitRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::floribot_engines::interface_kitRequest_<ContainerAllocator1> & lhs, const ::floribot_engines::interface_kitRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.value_type == rhs.value_type &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::floribot_engines::interface_kitRequest_<ContainerAllocator1> & lhs, const ::floribot_engines::interface_kitRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace floribot_engines

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::floribot_engines::interface_kitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::floribot_engines::interface_kitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::floribot_engines::interface_kitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::floribot_engines::interface_kitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::floribot_engines::interface_kitRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::floribot_engines::interface_kitRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::floribot_engines::interface_kitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "225c9deaf4e7ddb1539c5a9bdaa7a28f";
  }

  static const char* value(const ::floribot_engines::interface_kitRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x225c9deaf4e7ddb1ULL;
  static const uint64_t static_value2 = 0x539c5a9bdaa7a28fULL;
};

template<class ContainerAllocator>
struct DataType< ::floribot_engines::interface_kitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "floribot_engines/interface_kitRequest";
  }

  static const char* value(const ::floribot_engines::interface_kitRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::floribot_engines::interface_kitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n"
"int32 value_type\n"
"int32 value\n"
;
  }

  static const char* value(const ::floribot_engines::interface_kitRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::floribot_engines::interface_kitRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.value_type);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct interface_kitRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::floribot_engines::interface_kitRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::floribot_engines::interface_kitRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLORIBOT_ENGINES_MESSAGE_INTERFACE_KITREQUEST_H
