// Generated by gencpp from file floribot_engines/interface_kit_params.msg
// DO NOT EDIT!


#ifndef FLORIBOT_ENGINES_MESSAGE_INTERFACE_KIT_PARAMS_H
#define FLORIBOT_ENGINES_MESSAGE_INTERFACE_KIT_PARAMS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace floribot_engines
{
template <class ContainerAllocator>
struct interface_kit_params_
{
  typedef interface_kit_params_<ContainerAllocator> Type;

  interface_kit_params_()
    : header()
    , index(0)
    , value_type(0)
    , value(0)  {
    }
  interface_kit_params_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , index(0)
    , value_type(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _index_type;
  _index_type index;

   typedef int32_t _value_type_type;
  _value_type_type value_type;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::floribot_engines::interface_kit_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::floribot_engines::interface_kit_params_<ContainerAllocator> const> ConstPtr;

}; // struct interface_kit_params_

typedef ::floribot_engines::interface_kit_params_<std::allocator<void> > interface_kit_params;

typedef boost::shared_ptr< ::floribot_engines::interface_kit_params > interface_kit_paramsPtr;
typedef boost::shared_ptr< ::floribot_engines::interface_kit_params const> interface_kit_paramsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::floribot_engines::interface_kit_params_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::floribot_engines::interface_kit_params_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::floribot_engines::interface_kit_params_<ContainerAllocator1> & lhs, const ::floribot_engines::interface_kit_params_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.index == rhs.index &&
    lhs.value_type == rhs.value_type &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::floribot_engines::interface_kit_params_<ContainerAllocator1> & lhs, const ::floribot_engines::interface_kit_params_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace floribot_engines

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::floribot_engines::interface_kit_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::floribot_engines::interface_kit_params_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::floribot_engines::interface_kit_params_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::floribot_engines::interface_kit_params_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::floribot_engines::interface_kit_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::floribot_engines::interface_kit_params_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::floribot_engines::interface_kit_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b369436f357b4695ea7db89ef60fcefd";
  }

  static const char* value(const ::floribot_engines::interface_kit_params_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb369436f357b4695ULL;
  static const uint64_t static_value2 = 0xea7db89ef60fcefdULL;
};

template<class ContainerAllocator>
struct DataType< ::floribot_engines::interface_kit_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "floribot_engines/interface_kit_params";
  }

  static const char* value(const ::floribot_engines::interface_kit_params_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::floribot_engines::interface_kit_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 index\n"
"int32 value_type\n"
"int32 value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::floribot_engines::interface_kit_params_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::floribot_engines::interface_kit_params_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.index);
      stream.next(m.value_type);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct interface_kit_params_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::floribot_engines::interface_kit_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::floribot_engines::interface_kit_params_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLORIBOT_ENGINES_MESSAGE_INTERFACE_KIT_PARAMS_H
