// Generated by gencpp from file floribot_engines/interface_kitResponse.msg
// DO NOT EDIT!


#ifndef FLORIBOT_ENGINES_MESSAGE_INTERFACE_KITRESPONSE_H
#define FLORIBOT_ENGINES_MESSAGE_INTERFACE_KITRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace floribot_engines
{
template <class ContainerAllocator>
struct interface_kitResponse_
{
  typedef interface_kitResponse_<ContainerAllocator> Type;

  interface_kitResponse_()
    : ack(0)  {
    }
  interface_kitResponse_(const ContainerAllocator& _alloc)
    : ack(0)  {
  (void)_alloc;
    }



   typedef int32_t _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::floribot_engines::interface_kitResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::floribot_engines::interface_kitResponse_<ContainerAllocator> const> ConstPtr;

}; // struct interface_kitResponse_

typedef ::floribot_engines::interface_kitResponse_<std::allocator<void> > interface_kitResponse;

typedef boost::shared_ptr< ::floribot_engines::interface_kitResponse > interface_kitResponsePtr;
typedef boost::shared_ptr< ::floribot_engines::interface_kitResponse const> interface_kitResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::floribot_engines::interface_kitResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::floribot_engines::interface_kitResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::floribot_engines::interface_kitResponse_<ContainerAllocator1> & lhs, const ::floribot_engines::interface_kitResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ack == rhs.ack;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::floribot_engines::interface_kitResponse_<ContainerAllocator1> & lhs, const ::floribot_engines::interface_kitResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace floribot_engines

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::floribot_engines::interface_kitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::floribot_engines::interface_kitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::floribot_engines::interface_kitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::floribot_engines::interface_kitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::floribot_engines::interface_kitResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::floribot_engines::interface_kitResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::floribot_engines::interface_kitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35e806e08fe8e25fde5b4c88fa52f05b";
  }

  static const char* value(const ::floribot_engines::interface_kitResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35e806e08fe8e25fULL;
  static const uint64_t static_value2 = 0xde5b4c88fa52f05bULL;
};

template<class ContainerAllocator>
struct DataType< ::floribot_engines::interface_kitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "floribot_engines/interface_kitResponse";
  }

  static const char* value(const ::floribot_engines::interface_kitResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::floribot_engines::interface_kitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ack\n"
"\n"
;
  }

  static const char* value(const ::floribot_engines::interface_kitResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::floribot_engines::interface_kitResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct interface_kitResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::floribot_engines::interface_kitResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::floribot_engines::interface_kitResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ack: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLORIBOT_ENGINES_MESSAGE_INTERFACE_KITRESPONSE_H
